### ISSUE TITLE
Display table of user input (for export)

### ISSUE THREAD

**Issue by Aparus** [Aparus/frazy#13]
Because we are in beta version and don't give to users any guarantees, it is a good idea to give them ability to export all their work on our site into simple table format,  that they can save into text file, or google-spreadsheet. 
tsv: 
```
start end lang:Title trLang:trTitle
0.1 3.08 en:Chapter1 it:Capitolo1
```

**Comment by merryunbirthday** [comment]
Closed?

**Comment by Aparus** [comment]
> Closed?

yes )
