### ISSUE TITLE
Write cloud function for auto write Material.title to Unit.heading

### ISSUE THREAD

**Issue by Aparus** [Aparus/frazy#17]
On creating Material or changing its title, if it has Unit, we need to update that Unit's heading. 

Make a trigger function on `Material.changed`, then `diff(doc.before, doc.after)` and if Title has changed, a related item in Unit heading should change.

**Comment by merryunbirthday** [comment]
Is it different from issue # 5?

**Comment by Aparus** [comment]
> Is it different from issue # 5?

yes, thanks )
