### ISSUE TITLE
Sometimes on redirect phrases not loading

### ISSUE THREAD

**Issue by Aparus** [Aparus/frazy#6]
Instead of the page filled with data, you see just audio, maybe part of data like titles, but not phrases. If you redirect again or reload the page, everything works. 

With bug: 
![Screenshot from 2019-12-02 14-16-24](https://user-images.githubusercontent.com/1222611/69955305-6ff0d100-150e-11ea-8bf9-bbf1ab2d1424.png)

without bug: 
![Screenshot from 2019-12-02 14-16-39](https://user-images.githubusercontent.com/1222611/69955346-80a14700-150e-11ea-8727-b73a93e5b89c.png)

**Comment by merryunbirthday** [comment]
Is it still relevant?

**Comment by merryunbirthday** [comment]
What do you mean by 'redirect'?

**Comment by Aparus** [comment]
> Is it still relevant?

No. )
